exclude: |
  (?x)(
    ^node_modules/|
    ^mcp/node_modules/|
    \.lock$|
    ^\.venv/|
    ^rag/\.venv/|
    ^__pycache__/|
    \.pyc$
  )
repos:
  # Ruff: lint + format
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # Detect-Secrets (Yelp) para detectar claves/secretos
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]

  # Higiene básica
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
